### ISSUE TITLE
用户脚本的多项选择如何配置bind

### ISSUE THREAD

**Issue by porishor** [scriptscat/scriptcat.org#6]
![image](https://user-images.githubusercontent.com/123872348/219952159-becabced-cd9e-4be7-a757-b978b2fead5f.png)
然后捏，，通过什么地方设置里面的cookie

**Comment by CodFrm** [comment]
新版本中有bug，手动安装这个试试：https://github.com/scriptscat/scriptcat/actions/runs/4228624356

在储存中设置好一个array的值，例如这样:(工具->储存管理),这个值也可以使用 GM_setValue设置

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/22783163/220230877-2fefacf8-1457-4e77-a05e-f42d2e20a021.png">

然后就可以了：

<img width="539" alt="image" src="https://user-images.githubusercontent.com/22783163/220230997-2d90e7af-4ab5-4d6c-b88c-e7b517c043b2.png">

**Comment by porishor** [comment]
> 新版本中有bug，手动安装这个试试：https://github.com/scriptscat/scriptcat/actions/runs/4228624356
> 
> 在储存中设置好一个array的值，例如这样:(工具->储存管理),这个值也可以使用 GM_setValue设置
> 
> <img alt="image" width="1087" src="https://user-images.githubusercontent.com/22783163/220230877-2fefacf8-1457-4e77-a05e-f42d2e20a021.png">
> 
> 然后就可以了：
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/22783163/220230997-2d90e7af-4ab5-4d6c-b88c-e7b517c043b2.png">

谢谢作者大大亲自来回复，用户配置是个很好的功能。
![image](https://user-images.githubusercontent.com/123872348/220281197-47de39ab-0fd2-4b3a-93a6-82538ea4b8e3.png)
我不清楚自己是不是哪里做错了，但是我好像没有在工具中找到存储管理这一选项。我仍然用GM_setValue()设置了值，但是在配置面板里面没有效果。

**Comment by CodFrm** [comment]
@porishor 不是在工具里，在脚本编辑的这里

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/22783163/220498397-136319a4-74aa-4147-bd72-043132f0c900.png">

**Comment by porishor** [comment]
成功了，感谢😊
